### ISSUE TITLE
Panic when execute example code

### ISSUE THREAD

**Issue by wildskyf** [flimzy/kivik#247] opened 2017-11-25 14:01 UTC
1. Which version of Kivik are you using?
37658b7bc

2. Which version of Go are you using? (Output of `go version`) -- Kivik 1.0 aims to support all versions of Go from 1.7
`go version go1.9.1 linux/amd64`

3. What did you do? (Include your code if possible)

copy and paste the example code in [README](https://github.com/flimzy/kivik#example-usage)

4. What did you expect to see?

no error

5. What did you see instead?

panic: io: read/write on closed pipe

```
goroutine 1 [running]:
main.main()
	path-to-file.go:53 +0x449
exit status 2
```

**Comment by flimzy** [comment] 2017-11-25 16:42
You haven't shown me your exact code, and I know it's not identical to the readme, because the readme doesn't contain 53 lines :)

But this is probably expected behavior if the server connection fails.  The error message is, however, misleading.  I will attempt to fix that shortly.

**Comment by wildskyf** [comment] 2017-11-26 05:24
oh that's my fault.
I commented some other codes, so it should be on line 30 like this:

```
panic: io: read/write on closed pipe

goroutine 1 [running]:
main.main()
	/home/wildsky/Playground/src/kivik/main.go:30 +0x3ef
exit status 2

```

**Comment by flimzy** [comment] 2017-11-26 17:46
This should be fixed now; running the same test against the latest Kivik code should result in a more meaningful error.

**Closed** 2017-11-26 17:45 UTC
Labels: bug, enhancement

**Comment by wildskyf** [comment] 2017-12-03 12:02
yeah, it become `panic: Not Found: no_db_file` now.

**Comment by wildskyf** [comment] 2017-12-03 12:06
ohh... I need to `curl -X PUT http://localhost:5984/animals` first!
Thanks for your better debug info. It does help me! :)
